# Generated by Django 4.2.11 on 2026-07-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Decora Nine Interiors Pvt. Ltd.', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('phone', models.CharField(default='7306876887', max_length=20)),
                ('whatsapp_number', models.CharField(default='7306876887', max_length=20)),
                ('email', models.EmailField(default='decoranine@gmail.com', max_length=254)),
                ('address', models.TextField(default='13/4, 3rd cross, 2nd Main, New Extension, Madiwala, Bangalore, 560068')),
                ('business_hours', models.CharField(default='Mon-Sat: 10:00 AM - 6:00 PM, Sun: Closed', max_length=200)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('footer_description', models.TextField(default='Decora Nine Interiors specializes in creating beautiful, functional spaces.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
